[package]
name = "ohkami-nio"
version = "0.0.0"
edition = "2024"
publish = false

[profile.release]
lto           = true
panic         = "abort"
codegen-units = 1

[dependencies]
ohkami = { version = "0.24", features = ["rt_nio"] }
nio    = { version = "0.0" }